# Generated by Django 2.0.2 on 2018-11-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('blogNote', models.CharField(max_length=500)),
                ('enabled', models.BooleanField()),
            ],
        ),
    ]
