# Generated by Django 2.0.2 on 2018-11-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/FEgif2.gif', upload_to='images/'),
        ),
    ]
