# Generated by Django 2.0.2 on 2018-11-05 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogNote',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pubDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 21, 5, 27, 82549)),
        ),
    ]
