# Generated by Django 2.0.2 on 2018-11-06 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181105_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pubDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 20, 22, 7, 241269)),
        ),
    ]
