# Generated by Django 2.0.2 on 2018-11-06 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181106_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pubDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 20, 34, 44, 427432)),
        ),
    ]
