# Generated by Django 2.0.2 on 2018-11-07 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181107_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogTitle',
            field=models.CharField(default='Blog Title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='pubDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 18, 37, 24, 551953)),
        ),
    ]
